### ISSUE TITLE
random seed seems not work

### ISSUE THREAD

**Issue by fiberleif** [DartML/PPO-Stein-Control-Variate#4]
hi, it seems not work for setting same random seed to generate same results, do you find this issue?

Thanks!

**Comment by lewisKit** [comment]
hi, sorry for late response. 

It is possible to run the same settings with the same random seed to generate different results. It might be that you are using multiple cpu system along with other experiments. if you run the ppo code from openai baselines, you will also find the same [issue](https://github.com/openai/baselines/issues/65).

In our experiments, we use the 4-core AWS instance from the same mirror to run a single experiment, which would make the experiment results more stable.
